server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8080
              predicates:
                - Path= ${app.api-prefix}/users/**

            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/auth/**

            - id: hotel-service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/hotels/**, /api/v1/room-types/**, /uploads/** , /api/v1/files/**, /api/v1/roomTypes/**

            - id: booking-service
              uri: http://localhost:8083
              predicates:
                - Path=${app.api-prefix}/bookings/**

            - id: chat-service
              uri: http://localhost:8089
              predicates:
                - Path= ${app.api-prefix}/chats/**

            - id: review-service
              uri: http://localhost:8086
              predicates:
                - Path= ${app.api-prefix}/reviews/**
